name: 'Common Setup'
description: 'Checkout repo, setup Node.js, install Bun, cache dependencies'

inputs:
  node-version:
    required: false
    default: '24.11.1'
  bun-version:
    required: false
    default: '1.3.3'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js v${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Bun v${{ inputs.bun-version }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun
          ~/.cache/bun
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
