name: 'Common Setup'
description: 'Install Node, Bun and cache dependencies for CI'

inputs:
  node-version:
    required: false
    default: '24'
  bun-version:
    required: false
    default: '1.3.5'

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: |
          ~/.bun
          ~/.cache/bun
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
