name: 'Bug'
description: 'Report a reproducible bug.'

labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        > Please use this form for reproducible bugs.  
        > If you unsure it’s a bug, consider using Discussions.

  - type: textarea
    id: environment
    attributes:
      label: 'Environment'
      description: Add any relevant environment details.
      placeholder: |
        Echo version: 0.5.0
        Node version: 24.13.0
        Runtime: Chrome 122 / Next.js 16 / Bun 1.3.9
        OS: Windows 10, macOS 15, etc.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what went wrong.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 'Actual behavior'
      description: What actually happened?
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: Add any extra details.
    validations:
      required: false
