name: 'Documentation'
description: 'Report missing, unclear, or incorrect documentation.'

labels: ['documentation']

body:
  - type: textarea
    id: summary
    attributes:
      label: 'Summary'
      description: Briefly describe what is missing, unclear, or incorrect.
      placeholder: e.g. "Interceptor examples do not show how to handle async errors."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: 'Where is this?'
      description: Link to the page or file, or specify the section.
      placeholder: e.g. "README.md – Interceptors section" or a direct URL
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 'Suggested improvement (optional)'
      description: If you have an idea for better wording or examples, add it here.
      placeholder: You could change the example to...
    validations:
      required: false
