name: 'Feature request'
description: 'Suggest an idea or feature.'

labels: ['feature']

body:
  - type: markdown
    attributes:
      value: |
        Use this form to propose a new feature or improvement.  
        Please check existing issues first to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: 'What problem would this feature solve?'
      description: Describe the use case or pain point.
      placeholder: I'm always running into this issue when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 'Proposed solution'
      description: Describe what you’d like Echo to do.
      placeholder: It would be helpful if Echo could [...]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: Add any extra details.
    validations:
      required: false
